services:
  api:
    build: .
    container_name: api_practice_1
    volumes:
      - .:/app
      - shared-media:/shared
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    command: uvicorn first_practice:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - FFMPEG_CONTAINER=ffmpeg_tool_practice_1
    depends_on:
      - ffmpeg_tool

  ffmpeg_tool:
    build:
      context: ./ffmpeg_ex2
      dockerfile: Dockerfile
    container_name: ffmpeg_tool_practice_1
    volumes:
      - shared-media:/shared
    entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]

volumes:
  shared-media:
